[project]
name = "ppstructure-cuda-service"
version = "0.1.0"
description = "PP-StructureV3 service for NVIDIA CUDA"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "paddlepaddle-gpu==3.3.0",
    "paddleocr[doc-parser]",
    "paddlex[serving]",


    # PaddleOCR-VL vLLM 服务
    "torch==2.8.0",
    "vllm==0.10.2",
    "flash-attn==2.8.2",
    "transformers==4.57.6",
    "tokenizers==0.22.1",
]



[[tool.uv.index]]
name = "paddle-cu118"
url = "https://www.paddlepaddle.org.cn/packages/stable/cu118/"
explicit = true

[[tool.uv.index]]
name = "pypi-cn"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.uv.sources]
paddlepaddle-gpu = { index = "paddle-cu118" }
